# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IsoldeFrame.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_isolde_widget(object):
    def setupUi(self, isolde_widget):
        isolde_widget.setObjectName("isolde_widget")
        isolde_widget.resize(547, 966)
        isolde_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        isolde_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(isolde_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self._isolde_icon = QtWidgets.QLabel(isolde_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._isolde_icon.sizePolicy().hasHeightForWidth())
        self._isolde_icon.setSizePolicy(sizePolicy)
        self._isolde_icon.setMaximumSize(QtCore.QSize(50, 65))
        self._isolde_icon.setText("")
        self._isolde_icon.setPixmap(QtGui.QPixmap("../../.designer/backup/resources/logo_small.png"))
        self._isolde_icon.setScaledContents(True)
        self._isolde_icon.setObjectName("_isolde_icon")
        self.horizontalLayout_17.addWidget(self._isolde_icon)
        self.frame = QtWidgets.QFrame(isolde_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setTextFormat(QtCore.Qt.AutoText)
        self.label_32.setScaledContents(False)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_29.addWidget(self.label_32)
        self._master_model_combo_box = QtWidgets.QComboBox(self.frame)
        self._master_model_combo_box.setObjectName("_master_model_combo_box")
        self.horizontalLayout_29.addWidget(self._master_model_combo_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem)
        self.horizontalLayout_17.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.toolBox = QtWidgets.QToolBox(isolde_widget)
        self.toolBox.setObjectName("toolBox")
        self._build_page = QtWidgets.QWidget()
        self._build_page.setGeometry(QtCore.QRect(0, 0, 527, 707))
        self._build_page.setObjectName("_build_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self._build_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self._build_tab_widget = QtWidgets.QTabWidget(self._build_page)
        self._build_tab_widget.setObjectName("_build_tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self._build_tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self._build_tab_widget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self._build_tab_widget)
        self.toolBox.addItem(self._build_page, "")
        self._simulate_page = QtWidgets.QWidget()
        self._simulate_page.setGeometry(QtCore.QRect(0, 0, 527, 707))
        self._simulate_page.setObjectName("_simulate_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._simulate_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self._sim_tab_widget = QtWidgets.QTabWidget(self._simulate_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self._sim_tab_widget.sizePolicy().hasHeightForWidth())
        self._sim_tab_widget.setSizePolicy(sizePolicy)
        self._sim_tab_widget.setObjectName("_sim_tab_widget")
        self._sim_basic_tab = QtWidgets.QWidget()
        self._sim_basic_tab.setObjectName("_sim_basic_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self._sim_basic_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self._sim_basic_tab_scroll_area = QtWidgets.QScrollArea(self._sim_basic_tab)
        self._sim_basic_tab_scroll_area.setWidgetResizable(True)
        self._sim_basic_tab_scroll_area.setObjectName("_sim_basic_tab_scroll_area")
        self._sim_basic_scroll_area_contents = QtWidgets.QWidget()
        self._sim_basic_scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 470, 1158))
        self._sim_basic_scroll_area_contents.setObjectName("_sim_basic_scroll_area_contents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self._sim_basic_scroll_area_contents)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self._sim_basic_selection_mode_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        self._sim_basic_selection_mode_frame.setMinimumSize(QtCore.QSize(0, 100))
        self._sim_basic_selection_mode_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_selection_mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_selection_mode_frame.setObjectName("_sim_basic_selection_mode_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self._sim_basic_selection_mode_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._sim_basic_selection_mode_group_box = QtWidgets.QGroupBox(self._sim_basic_selection_mode_frame)
        self._sim_basic_selection_mode_group_box.setObjectName("_sim_basic_selection_mode_group_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self._sim_basic_selection_mode_group_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._sim_basic_by_selected_atoms_button = QtWidgets.QRadioButton(self._sim_basic_selection_mode_group_box)
        self._sim_basic_by_selected_atoms_button.setChecked(True)
        self._sim_basic_by_selected_atoms_button.setObjectName("_sim_basic_by_selected_atoms_button")
        self.gridLayout_3.addWidget(self._sim_basic_by_selected_atoms_button, 0, 0, 1, 1)
        self._sim_basic_by_chain_button = QtWidgets.QRadioButton(self._sim_basic_selection_mode_group_box)
        self._sim_basic_by_chain_button.setObjectName("_sim_basic_by_chain_button")
        self.gridLayout_3.addWidget(self._sim_basic_by_chain_button, 0, 1, 1, 1)
        self._sim_basic_whole_structure_button = QtWidgets.QRadioButton(self._sim_basic_selection_mode_group_box)
        self._sim_basic_whole_structure_button.setObjectName("_sim_basic_whole_structure_button")
        self.gridLayout_3.addWidget(self._sim_basic_whole_structure_button, 1, 0, 1, 1)
        self._sim_basic_custom_selection_button = QtWidgets.QRadioButton(self._sim_basic_selection_mode_group_box)
        self._sim_basic_custom_selection_button.setObjectName("_sim_basic_custom_selection_button")
        self.gridLayout_3.addWidget(self._sim_basic_custom_selection_button, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self._sim_basic_selection_mode_group_box, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self._sim_basic_selection_mode_frame)
        self._sim_basic_mobile_selection_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._sim_basic_mobile_selection_frame.sizePolicy().hasHeightForWidth())
        self._sim_basic_mobile_selection_frame.setSizePolicy(sizePolicy)
        self._sim_basic_mobile_selection_frame.setMinimumSize(QtCore.QSize(0, 0))
        self._sim_basic_mobile_selection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_mobile_selection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_mobile_selection_frame.setObjectName("_sim_basic_mobile_selection_frame")
        self.formLayout = QtWidgets.QFormLayout(self._sim_basic_mobile_selection_frame)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self._sim_basic_mobile_selection_frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self._sim_basic_mobile_selection_frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self._sim_basic_mobile_b_and_a_spinbox = QtWidgets.QSpinBox(self._sim_basic_mobile_selection_frame)
        self._sim_basic_mobile_b_and_a_spinbox.setProperty("value", 5)
        self._sim_basic_mobile_b_and_a_spinbox.setObjectName("_sim_basic_mobile_b_and_a_spinbox")
        self.horizontalLayout_4.addWidget(self._sim_basic_mobile_b_and_a_spinbox)
        self.label_4 = QtWidgets.QLabel(self._sim_basic_mobile_selection_frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self._sim_basic_mobile_selection_frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self._sim_basic_mobile_sel_within_spinbox = QtWidgets.QSpinBox(self._sim_basic_mobile_selection_frame)
        self._sim_basic_mobile_sel_within_spinbox.setProperty("value", 5)
        self._sim_basic_mobile_sel_within_spinbox.setObjectName("_sim_basic_mobile_sel_within_spinbox")
        self.horizontalLayout_5.addWidget(self._sim_basic_mobile_sel_within_spinbox)
        self.label_6 = QtWidgets.QLabel(self._sim_basic_mobile_selection_frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self._sim_basic_mobile_sel_backbone_checkbox = QtWidgets.QCheckBox(self._sim_basic_mobile_selection_frame)
        self._sim_basic_mobile_sel_backbone_checkbox.setChecked(True)
        self._sim_basic_mobile_sel_backbone_checkbox.setObjectName("_sim_basic_mobile_sel_backbone_checkbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self._sim_basic_mobile_sel_backbone_checkbox)
        self.verticalLayout_8.addWidget(self._sim_basic_mobile_selection_frame)
        self._sim_basic_mobile_by_chain_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._sim_basic_mobile_by_chain_frame.sizePolicy().hasHeightForWidth())
        self._sim_basic_mobile_by_chain_frame.setSizePolicy(sizePolicy)
        self._sim_basic_mobile_by_chain_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self._sim_basic_mobile_by_chain_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_mobile_by_chain_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_mobile_by_chain_frame.setObjectName("_sim_basic_mobile_by_chain_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self._sim_basic_mobile_by_chain_frame)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self._sim_basic_mobile_by_chain_frame)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self._sim_basic_mobile_chains_list_box = QtWidgets.QListWidget(self._sim_basic_mobile_by_chain_frame)
        self._sim_basic_mobile_chains_list_box.setMinimumSize(QtCore.QSize(80, 80))
        self._sim_basic_mobile_chains_list_box.setMaximumSize(QtCore.QSize(60, 50))
        self._sim_basic_mobile_chains_list_box.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self._sim_basic_mobile_chains_list_box.setObjectName("_sim_basic_mobile_chains_list_box")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._sim_basic_mobile_chains_list_box)
        self.horizontalLayout_14.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self._sim_basic_mobile_chains_surrounds_label1 = QtWidgets.QLabel(self._sim_basic_mobile_by_chain_frame)
        self._sim_basic_mobile_chains_surrounds_label1.setWordWrap(True)
        self._sim_basic_mobile_chains_surrounds_label1.setObjectName("_sim_basic_mobile_chains_surrounds_label1")
        self.verticalLayout_9.addWidget(self._sim_basic_mobile_chains_surrounds_label1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self._sim_basic_mobile_chains_within_spin_box = QtWidgets.QSpinBox(self._sim_basic_mobile_by_chain_frame)
        self._sim_basic_mobile_chains_within_spin_box.setProperty("value", 5)
        self._sim_basic_mobile_chains_within_spin_box.setObjectName("_sim_basic_mobile_chains_within_spin_box")
        self.horizontalLayout_6.addWidget(self._sim_basic_mobile_chains_within_spin_box)
        self.label_9 = QtWidgets.QLabel(self._sim_basic_mobile_by_chain_frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self._sim_basic_mobile_chain_backbone_checkbox = QtWidgets.QCheckBox(self._sim_basic_mobile_by_chain_frame)
        self._sim_basic_mobile_chain_backbone_checkbox.setText("")
        self._sim_basic_mobile_chain_backbone_checkbox.setChecked(True)
        self._sim_basic_mobile_chain_backbone_checkbox.setObjectName("_sim_basic_mobile_chain_backbone_checkbox")
        self.horizontalLayout_13.addWidget(self._sim_basic_mobile_chain_backbone_checkbox)
        self.label_11 = QtWidgets.QLabel(self._sim_basic_mobile_by_chain_frame)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.addWidget(self._sim_basic_mobile_by_chain_frame)
        self._sim_basic_mobile_custom_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        self._sim_basic_mobile_custom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_mobile_custom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_mobile_custom_frame.setObjectName("_sim_basic_mobile_custom_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self._sim_basic_mobile_custom_frame)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self._sim_basic_mobile_custom_frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self._sim_basic_mobile_custom_entry = QtWidgets.QLineEdit(self._sim_basic_mobile_custom_frame)
        self._sim_basic_mobile_custom_entry.setObjectName("_sim_basic_mobile_custom_entry")
        self.horizontalLayout_16.addWidget(self._sim_basic_mobile_custom_entry)
        self.verticalLayout_8.addWidget(self._sim_basic_mobile_custom_frame)
        self._sim_basic_mode_choice_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._sim_basic_mode_choice_frame.sizePolicy().hasHeightForWidth())
        self._sim_basic_mode_choice_frame.setSizePolicy(sizePolicy)
        self._sim_basic_mode_choice_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_mode_choice_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_mode_choice_frame.setObjectName("_sim_basic_mode_choice_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self._sim_basic_mode_choice_frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self._sim_basic_mode_combo_box = QtWidgets.QComboBox(self._sim_basic_mode_choice_frame)
        self._sim_basic_mode_combo_box.setObjectName("_sim_basic_mode_combo_box")
        self._sim_basic_mode_combo_box.addItem("")
        self._sim_basic_mode_combo_box.addItem("")
        self._sim_basic_mode_combo_box.addItem("")
        self.horizontalLayout_8.addWidget(self._sim_basic_mode_combo_box)
        self.verticalLayout_8.addWidget(self._sim_basic_mode_choice_frame)
        self._sim_basic_xtal_map_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._sim_basic_xtal_map_frame.sizePolicy().hasHeightForWidth())
        self._sim_basic_xtal_map_frame.setSizePolicy(sizePolicy)
        self._sim_basic_xtal_map_frame.setMinimumSize(QtCore.QSize(0, 0))
        self._sim_basic_xtal_map_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_xtal_map_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_xtal_map_frame.setObjectName("_sim_basic_xtal_map_frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self._sim_basic_xtal_map_frame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self._sim_basic_xtal_init_open_button = QtWidgets.QPushButton(self._sim_basic_xtal_map_frame)
        self._sim_basic_xtal_init_open_button.setMinimumSize(QtCore.QSize(0, 0))
        self._sim_basic_xtal_init_open_button.setObjectName("_sim_basic_xtal_init_open_button")
        self.verticalLayout_17.addWidget(self._sim_basic_xtal_init_open_button)
        self._sim_basic_xtal_init_main_frame = QtWidgets.QFrame(self._sim_basic_xtal_map_frame)
        self._sim_basic_xtal_init_main_frame.setObjectName("_sim_basic_xtal_init_main_frame")
        self._sim_basic_xtal_init_frame = QtWidgets.QVBoxLayout(self._sim_basic_xtal_init_main_frame)
        self._sim_basic_xtal_init_frame.setContentsMargins(0, 0, 0, 0)
        self._sim_basic_xtal_init_frame.setObjectName("_sim_basic_xtal_init_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self._sim_basic_xtal_init_main_frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self._sim_basic_xtal_init_model_combo_box = QtWidgets.QComboBox(self._sim_basic_xtal_init_main_frame)
        self._sim_basic_xtal_init_model_combo_box.setObjectName("_sim_basic_xtal_init_model_combo_box")
        self.horizontalLayout_9.addWidget(self._sim_basic_xtal_init_model_combo_box)
        self._sim_basic_xtal_init_reflections_file_button = QtWidgets.QPushButton(self._sim_basic_xtal_init_main_frame)
        self._sim_basic_xtal_init_reflections_file_button.setMinimumSize(QtCore.QSize(0, 0))
        self._sim_basic_xtal_init_reflections_file_button.setObjectName("_sim_basic_xtal_init_reflections_file_button")
        self.horizontalLayout_9.addWidget(self._sim_basic_xtal_init_reflections_file_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self._sim_basic_xtal_init_reflections_file_name = QtWidgets.QLineEdit(self._sim_basic_xtal_init_main_frame)
        self._sim_basic_xtal_init_reflections_file_name.setObjectName("_sim_basic_xtal_init_reflections_file_name")
        self.horizontalLayout_9.addWidget(self._sim_basic_xtal_init_reflections_file_name)
        self._sim_basic_xtal_init_frame.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self._sim_basic_xtal_init_go_button = QtWidgets.QPushButton(self._sim_basic_xtal_init_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._sim_basic_xtal_init_go_button.sizePolicy().hasHeightForWidth())
        self._sim_basic_xtal_init_go_button.setSizePolicy(sizePolicy)
        self._sim_basic_xtal_init_go_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self._sim_basic_xtal_init_go_button.setObjectName("_sim_basic_xtal_init_go_button")
        self.horizontalLayout_26.addWidget(self._sim_basic_xtal_init_go_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem3)
        self._sim_basic_xtal_init_done_button = QtWidgets.QPushButton(self._sim_basic_xtal_init_main_frame)
        self._sim_basic_xtal_init_done_button.setObjectName("_sim_basic_xtal_init_done_button")
        self.horizontalLayout_26.addWidget(self._sim_basic_xtal_init_done_button)
        self._sim_basic_xtal_init_frame.addLayout(self.horizontalLayout_26)
        self.verticalLayout_17.addWidget(self._sim_basic_xtal_init_main_frame)
        self.verticalLayout_8.addWidget(self._sim_basic_xtal_map_frame)
        self._sim_basic_em_map_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._sim_basic_em_map_frame.sizePolicy().hasHeightForWidth())
        self._sim_basic_em_map_frame.setSizePolicy(sizePolicy)
        self._sim_basic_em_map_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_basic_em_map_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_basic_em_map_frame.setObjectName("_sim_basic_em_map_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self._sim_basic_em_map_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self._em_map_chooser_frame = QtWidgets.QFrame(self._sim_basic_em_map_frame)
        self._em_map_chooser_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._em_map_chooser_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._em_map_chooser_frame.setObjectName("_em_map_chooser_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self._em_map_chooser_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self._em_map_name_field = QtWidgets.QLineEdit(self._em_map_chooser_frame)
        self._em_map_name_field.setObjectName("_em_map_name_field")
        self.horizontalLayout_11.addWidget(self._em_map_name_field)
        self.label_13 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self._em_map_model_combo_box = QtWidgets.QComboBox(self._em_map_chooser_frame)
        self._em_map_model_combo_box.setObjectName("_em_map_model_combo_box")
        self.horizontalLayout_11.addWidget(self._em_map_model_combo_box)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self._em_map_cutoff_spin_box = QtWidgets.QDoubleSpinBox(self._em_map_chooser_frame)
        self._em_map_cutoff_spin_box.setDecimals(1)
        self._em_map_cutoff_spin_box.setMaximum(50.0)
        self._em_map_cutoff_spin_box.setProperty("value", 3.0)
        self._em_map_cutoff_spin_box.setObjectName("_em_map_cutoff_spin_box")
        self.horizontalLayout_10.addWidget(self._em_map_cutoff_spin_box)
        self.label_15 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self._em_map_coupling_spin_box = QtWidgets.QDoubleSpinBox(self._em_map_chooser_frame)
        self._em_map_coupling_spin_box.setDecimals(1)
        self._em_map_coupling_spin_box.setMaximum(1000.0)
        self._em_map_coupling_spin_box.setProperty("value", 10.0)
        self._em_map_coupling_spin_box.setObjectName("_em_map_coupling_spin_box")
        self.horizontalLayout_10.addWidget(self._em_map_coupling_spin_box)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self._em_map_style_combo_box = QtWidgets.QComboBox(self._em_map_chooser_frame)
        self._em_map_style_combo_box.setObjectName("_em_map_style_combo_box")
        self.gridLayout_5.addWidget(self._em_map_style_combo_box, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 2, 1, 1)
        self._em_map_color_combo_box = QtWidgets.QComboBox(self._em_map_chooser_frame)
        self._em_map_color_combo_box.setObjectName("_em_map_color_combo_box")
        self.gridLayout_5.addWidget(self._em_map_color_combo_box, 0, 3, 1, 1)
        self._em_map_masked_checkbox = QtWidgets.QCheckBox(self._em_map_chooser_frame)
        self._em_map_masked_checkbox.setChecked(True)
        self._em_map_masked_checkbox.setObjectName("_em_map_masked_checkbox")
        self.gridLayout_5.addWidget(self._em_map_masked_checkbox, 1, 3, 1, 1)
        self._em_map_contour_spin_box = QtWidgets.QDoubleSpinBox(self._em_map_chooser_frame)
        self._em_map_contour_spin_box.setMinimum(-9999.99)
        self._em_map_contour_spin_box.setMaximum(9999.99)
        self._em_map_contour_spin_box.setSingleStep(0.1)
        self._em_map_contour_spin_box.setProperty("value", 1.0)
        self._em_map_contour_spin_box.setObjectName("_em_map_contour_spin_box")
        self.gridLayout_5.addWidget(self._em_map_contour_spin_box, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self._em_map_chooser_frame)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 0, 1, 1)
        self._em_map_contour_units_combo_box = QtWidgets.QComboBox(self._em_map_chooser_frame)
        self._em_map_contour_units_combo_box.setObjectName("_em_map_contour_units_combo_box")
        self.gridLayout_5.addWidget(self._em_map_contour_units_combo_box, 1, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_5)
        self.frame_2 = QtWidgets.QFrame(self._em_map_chooser_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self._em_map_chooser_combo_box = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._em_map_chooser_combo_box.sizePolicy().hasHeightForWidth())
        self._em_map_chooser_combo_box.setSizePolicy(sizePolicy)
        self._em_map_chooser_combo_box.setMinimumSize(QtCore.QSize(100, 0))
        self._em_map_chooser_combo_box.setObjectName("_em_map_chooser_combo_box")
        self.horizontalLayout_15.addWidget(self._em_map_chooser_combo_box)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self._em_map_set_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._em_map_set_button.sizePolicy().hasHeightForWidth())
        self._em_map_set_button.setSizePolicy(sizePolicy)
        self._em_map_set_button.setObjectName("_em_map_set_button")
        self.horizontalLayout_15.addWidget(self._em_map_set_button)
        self._em_map_remove_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._em_map_remove_button.sizePolicy().hasHeightForWidth())
        self._em_map_remove_button.setSizePolicy(sizePolicy)
        self._em_map_remove_button.setObjectName("_em_map_remove_button")
        self.horizontalLayout_15.addWidget(self._em_map_remove_button)
        self._em_map_done_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._em_map_done_button.sizePolicy().hasHeightForWidth())
        self._em_map_done_button.setSizePolicy(sizePolicy)
        self._em_map_done_button.setObjectName("_em_map_done_button")
        self.horizontalLayout_15.addWidget(self._em_map_done_button)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.gridLayout_4.addWidget(self._em_map_chooser_frame, 1, 0, 1, 1)
        self._sim_basic_em_map_button = QtWidgets.QPushButton(self._sim_basic_em_map_frame)
        self._sim_basic_em_map_button.setObjectName("_sim_basic_em_map_button")
        self.gridLayout_4.addWidget(self._sim_basic_em_map_button, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self._sim_basic_em_map_frame)
        self._force_field_selection_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        self._force_field_selection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._force_field_selection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._force_field_selection_frame.setObjectName("_force_field_selection_frame")
        self.gridLayout = QtWidgets.QGridLayout(self._force_field_selection_frame)
        self.gridLayout.setObjectName("gridLayout")
        self._sim_force_field_selection_label = QtWidgets.QLabel(self._force_field_selection_frame)
        self._sim_force_field_selection_label.setObjectName("_sim_force_field_selection_label")
        self.gridLayout.addWidget(self._sim_force_field_selection_label, 0, 0, 1, 1)
        self._sim_force_field_combo_box = QtWidgets.QComboBox(self._force_field_selection_frame)
        self._sim_force_field_combo_box.setObjectName("_sim_force_field_combo_box")
        self.gridLayout.addWidget(self._sim_force_field_combo_box, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self._sim_water_model_selection_label = QtWidgets.QLabel(self._force_field_selection_frame)
        self._sim_water_model_selection_label.setObjectName("_sim_water_model_selection_label")
        self.gridLayout.addWidget(self._sim_water_model_selection_label, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        self._sim_water_model_combo_box = QtWidgets.QComboBox(self._force_field_selection_frame)
        self._sim_water_model_combo_box.setObjectName("_sim_water_model_combo_box")
        self.gridLayout.addWidget(self._sim_water_model_combo_box, 1, 2, 1, 1)
        self.verticalLayout_8.addWidget(self._force_field_selection_frame)
        self._sim_platform_frame = QtWidgets.QFrame(self._sim_basic_scroll_area_contents)
        self._sim_platform_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._sim_platform_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._sim_platform_frame.setObjectName("_sim_platform_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self._sim_platform_frame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(self._sim_platform_frame)
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self._sim_platform_combo_box = QtWidgets.QComboBox(self._sim_platform_frame)
        self._sim_platform_combo_box.setObjectName("_sim_platform_combo_box")
        self.horizontalLayout_12.addWidget(self._sim_platform_combo_box)
        self.verticalLayout_8.addWidget(self._sim_platform_frame)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self._sim_basic_mobile_selection_frame.raise_()
        self._sim_basic_mode_choice_frame.raise_()
        self._sim_basic_em_map_frame.raise_()
        self._sim_basic_xtal_map_frame.raise_()
        self._force_field_selection_frame.raise_()
        self._sim_platform_frame.raise_()
        self._sim_basic_selection_mode_frame.raise_()
        self._sim_basic_mobile_custom_frame.raise_()
        self._sim_basic_mobile_by_chain_frame.raise_()
        self._sim_basic_tab_scroll_area.setWidget(self._sim_basic_scroll_area_contents)
        self.verticalLayout_5.addWidget(self._sim_basic_tab_scroll_area)
        self._sim_tab_widget.addTab(self._sim_basic_tab, "")
        self._sim_restrain_tab = QtWidgets.QWidget()
        self._sim_restrain_tab.setObjectName("_sim_restrain_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self._sim_restrain_tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self._restraints_scroll_area = QtWidgets.QScrollArea(self._sim_restrain_tab)
        self._restraints_scroll_area.setWidgetResizable(True)
        self._restraints_scroll_area.setObjectName("_restraints_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 483, 554))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self._restraints_peptide_bond_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self._restraints_peptide_bond_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._restraints_peptide_bond_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._restraints_peptide_bond_frame.setObjectName("_restraints_peptide_bond_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self._restraints_peptide_bond_frame)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self._restraints_pep_on_off_combo_box = QtWidgets.QComboBox(self._restraints_peptide_bond_frame)
        self._restraints_pep_on_off_combo_box.setMaximumSize(QtCore.QSize(80, 16777215))
        self._restraints_pep_on_off_combo_box.setObjectName("_restraints_pep_on_off_combo_box")
        self._restraints_pep_on_off_combo_box.addItem("")
        self._restraints_pep_on_off_combo_box.addItem("")
        self.horizontalLayout_18.addWidget(self._restraints_pep_on_off_combo_box)
        self.label_19 = QtWidgets.QLabel(self._restraints_peptide_bond_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self._restraints_pep_all_sel_combo_box = QtWidgets.QComboBox(self._restraints_peptide_bond_frame)
        self._restraints_pep_all_sel_combo_box.setMaximumSize(QtCore.QSize(80, 16777215))
        self._restraints_pep_all_sel_combo_box.setObjectName("_restraints_pep_all_sel_combo_box")
        self._restraints_pep_all_sel_combo_box.addItem("")
        self._restraints_pep_all_sel_combo_box.addItem("")
        self.horizontalLayout_18.addWidget(self._restraints_pep_all_sel_combo_box)
        self.label_20 = QtWidgets.QLabel(self._restraints_peptide_bond_frame)
        self.label_20.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self._restraints_pep_go_button = QtWidgets.QPushButton(self._restraints_peptide_bond_frame)
        self._restraints_pep_go_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self._restraints_pep_go_button.setObjectName("_restraints_pep_go_button")
        self.horizontalLayout_18.addWidget(self._restraints_pep_go_button)
        self.verticalLayout_14.addWidget(self._restraints_peptide_bond_frame)
        self._restraints_stub_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self._restraints_stub_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._restraints_stub_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._restraints_stub_frame.setObjectName("_restraints_stub_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self._restraints_stub_frame)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton = QtWidgets.QPushButton(self._restraints_stub_frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_19.addWidget(self.pushButton)
        self.verticalLayout_14.addWidget(self._restraints_stub_frame)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem8)
        self._restraints_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self._restraints_scroll_area)
        self._sim_tab_widget.addTab(self._sim_restrain_tab, "")
        self._sim_remodel_tab = QtWidgets.QWidget()
        self._sim_remodel_tab.setObjectName("_sim_remodel_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self._sim_remodel_tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self._sim_remodel_scroll_area = QtWidgets.QScrollArea(self._sim_remodel_tab)
        self._sim_remodel_scroll_area.setWidgetResizable(True)
        self._sim_remodel_scroll_area.setObjectName("_sim_remodel_scroll_area")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 483, 554))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self._rebuild_sel_residue_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self._rebuild_sel_residue_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._rebuild_sel_residue_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._rebuild_sel_residue_frame.setObjectName("_rebuild_sel_residue_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self._rebuild_sel_residue_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_28 = QtWidgets.QLabel(self._rebuild_sel_residue_frame)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 2, 0, 1, 1)
        self._rebuild_sel_res_pep_info = QtWidgets.QLabel(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_pep_info.setObjectName("_rebuild_sel_res_pep_info")
        self.gridLayout_6.addWidget(self._rebuild_sel_res_pep_info, 1, 2, 1, 2)
        self._rebuild_sel_res_rot_discard_button = QtWidgets.QPushButton(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_rot_discard_button.setObjectName("_rebuild_sel_res_rot_discard_button")
        self.gridLayout_6.addWidget(self._rebuild_sel_res_rot_discard_button, 3, 5, 1, 1)
        self._rebuild_sel_res_rot_target_button = QtWidgets.QPushButton(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_rot_target_button.setObjectName("_rebuild_sel_res_rot_target_button")
        self.gridLayout_6.addWidget(self._rebuild_sel_res_rot_target_button, 3, 3, 1, 2)
        self.label_25 = QtWidgets.QLabel(self._rebuild_sel_residue_frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 2)
        self._rebuild_sel_res_rot_info = QtWidgets.QLabel(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_rot_info.setObjectName("_rebuild_sel_res_rot_info")
        self.gridLayout_6.addWidget(self._rebuild_sel_res_rot_info, 2, 1, 1, 1)
        self._rebuild_sel_res_rot_commit_button = QtWidgets.QPushButton(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_rot_commit_button.setObjectName("_rebuild_sel_res_rot_commit_button")
        self.gridLayout_6.addWidget(self._rebuild_sel_res_rot_commit_button, 3, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self._rebuild_sel_residue_frame)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 1)
        self._rebuild_sel_res_pep_flip_button = QtWidgets.QPushButton(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_pep_flip_button.setObjectName("_rebuild_sel_res_pep_flip_button")
        self.gridLayout_6.addWidget(self._rebuild_sel_res_pep_flip_button, 1, 5, 1, 1)
        self._rebuild_sel_residue_info = QtWidgets.QLabel(self._rebuild_sel_residue_frame)
        self._rebuild_sel_residue_info.setObjectName("_rebuild_sel_residue_info")
        self.gridLayout_6.addWidget(self._rebuild_sel_residue_info, 0, 1, 1, 5)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self._rebuild_sel_res_last_rotamer_button = QtWidgets.QPushButton(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_last_rotamer_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/reverse_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._rebuild_sel_res_last_rotamer_button.setIcon(icon)
        self._rebuild_sel_res_last_rotamer_button.setObjectName("_rebuild_sel_res_last_rotamer_button")
        self.horizontalLayout_30.addWidget(self._rebuild_sel_res_last_rotamer_button)
        self._rebuild_sel_res_next_rotamer_button = QtWidgets.QPushButton(self._rebuild_sel_residue_frame)
        self._rebuild_sel_res_next_rotamer_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/play_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._rebuild_sel_res_next_rotamer_button.setIcon(icon1)
        self._rebuild_sel_res_next_rotamer_button.setObjectName("_rebuild_sel_res_next_rotamer_button")
        self.horizontalLayout_30.addWidget(self._rebuild_sel_res_next_rotamer_button)
        self.gridLayout_6.addLayout(self.horizontalLayout_30, 2, 5, 1, 1)
        self.verticalLayout_15.addWidget(self._rebuild_sel_residue_frame)
        spacerItem9 = QtWidgets.QSpacerItem(20, 420, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem9)
        self._sim_remodel_scroll_area.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_6.addWidget(self._sim_remodel_scroll_area)
        self._sim_tab_widget.addTab(self._sim_remodel_tab, "")
        self._sim_validate_tab = QtWidgets.QWidget()
        self._sim_validate_tab.setObjectName("_sim_validate_tab")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self._sim_validate_tab)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self._validate_scroll_area = QtWidgets.QScrollArea(self._sim_validate_tab)
        self._validate_scroll_area.setWidgetResizable(True)
        self._validate_scroll_area.setObjectName("_validate_scroll_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 470, 796))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self._validate_rama_stub_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self._validate_rama_stub_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._validate_rama_stub_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._validate_rama_stub_frame.setObjectName("_validate_rama_stub_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self._validate_rama_stub_frame)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_22 = QtWidgets.QLabel(self._validate_rama_stub_frame)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem10)
        self._validate_rama_show_button = QtWidgets.QPushButton(self._validate_rama_stub_frame)
        self._validate_rama_show_button.setObjectName("_validate_rama_show_button")
        self.horizontalLayout_21.addWidget(self._validate_rama_show_button)
        self.verticalLayout_12.addWidget(self._validate_rama_stub_frame)
        self._validate_rama_main_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self._validate_rama_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._validate_rama_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._validate_rama_main_frame.setObjectName("_validate_rama_main_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self._validate_rama_main_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_21 = QtWidgets.QLabel(self._validate_rama_main_frame)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem11)
        self._validate_rama_case_combo_box = QtWidgets.QComboBox(self._validate_rama_main_frame)
        self._validate_rama_case_combo_box.setObjectName("_validate_rama_case_combo_box")
        self._validate_rama_case_combo_box.addItem("")
        self._validate_rama_case_combo_box.addItem("")
        self._validate_rama_case_combo_box.addItem("")
        self._validate_rama_case_combo_box.addItem("")
        self._validate_rama_case_combo_box.addItem("")
        self._validate_rama_case_combo_box.addItem("")
        self.horizontalLayout_23.addWidget(self._validate_rama_case_combo_box)
        self._validate_rama_hide_button = QtWidgets.QPushButton(self._validate_rama_main_frame)
        self._validate_rama_hide_button.setObjectName("_validate_rama_hide_button")
        self.horizontalLayout_23.addWidget(self._validate_rama_hide_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self._validate_rama_plot_container = QtWidgets.QWidget(self._validate_rama_main_frame)
        self._validate_rama_plot_container.setMinimumSize(QtCore.QSize(350, 350))
        self._validate_rama_plot_container.setObjectName("_validate_rama_plot_container")
        self._validate_rama_plot_layout = QtWidgets.QVBoxLayout(self._validate_rama_plot_container)
        self._validate_rama_plot_layout.setContentsMargins(0, 0, 0, 0)
        self._validate_rama_plot_layout.setObjectName("_validate_rama_plot_layout")
        self.horizontalLayout_24.addWidget(self._validate_rama_plot_container)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self._validate_rama_sel_combo_box = QtWidgets.QComboBox(self._validate_rama_main_frame)
        self._validate_rama_sel_combo_box.setObjectName("_validate_rama_sel_combo_box")
        self._validate_rama_sel_combo_box.addItem("")
        self._validate_rama_sel_combo_box.addItem("")
        self.horizontalLayout_22.addWidget(self._validate_rama_sel_combo_box)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem13)
        self._validate_rama_go_button = QtWidgets.QPushButton(self._validate_rama_main_frame)
        self._validate_rama_go_button.setObjectName("_validate_rama_go_button")
        self.horizontalLayout_22.addWidget(self._validate_rama_go_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.verticalLayout_12.addWidget(self._validate_rama_main_frame)
        self._validate_pep_stub_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self._validate_pep_stub_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._validate_pep_stub_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._validate_pep_stub_frame.setObjectName("_validate_pep_stub_frame")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self._validate_pep_stub_frame)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_26 = QtWidgets.QLabel(self._validate_pep_stub_frame)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_25.addWidget(self.label_26)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem14)
        self._validate_pep_show_button = QtWidgets.QPushButton(self._validate_pep_stub_frame)
        self._validate_pep_show_button.setObjectName("_validate_pep_show_button")
        self.horizontalLayout_25.addWidget(self._validate_pep_show_button)
        self.verticalLayout_12.addWidget(self._validate_pep_stub_frame)
        self._validate_pep_main_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self._validate_pep_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._validate_pep_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._validate_pep_main_frame.setObjectName("_validate_pep_main_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self._validate_pep_main_frame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtWidgets.QLabel(self._validate_pep_main_frame)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem15)
        self._validate_pep_hide_button = QtWidgets.QPushButton(self._validate_pep_main_frame)
        self._validate_pep_hide_button.setObjectName("_validate_pep_hide_button")
        self.horizontalLayout_27.addWidget(self._validate_pep_hide_button)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self._validate_pep_cis_list = QtWidgets.QListWidget(self._validate_pep_main_frame)
        self._validate_pep_cis_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self._validate_pep_cis_list.setObjectName("_validate_pep_cis_list")
        self.gridLayout_7.addWidget(self._validate_pep_cis_list, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self._validate_pep_main_frame)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self._validate_pep_main_frame)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 0, 1, 1, 1)
        self._validate_pep_twisted_list = QtWidgets.QListWidget(self._validate_pep_main_frame)
        self._validate_pep_twisted_list.setObjectName("_validate_pep_twisted_list")
        self.gridLayout_7.addWidget(self._validate_pep_twisted_list, 1, 1, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_7)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem16)
        self._validate_pep_update_button = QtWidgets.QPushButton(self._validate_pep_main_frame)
        self._validate_pep_update_button.setObjectName("_validate_pep_update_button")
        self.horizontalLayout_28.addWidget(self._validate_pep_update_button)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        self.verticalLayout_12.addWidget(self._validate_pep_main_frame)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self._validate_scroll_area.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_20.addWidget(self._validate_scroll_area)
        self._sim_tab_widget.addTab(self._sim_validate_tab, "")
        self.verticalLayout.addWidget(self._sim_tab_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._sim_go_button = QtWidgets.QToolButton(self._simulate_page)
        self._sim_go_button.setObjectName("_sim_go_button")
        self.horizontalLayout.addWidget(self._sim_go_button)
        self._sim_pause_button = QtWidgets.QToolButton(self._simulate_page)
        self._sim_pause_button.setObjectName("_sim_pause_button")
        self.horizontalLayout.addWidget(self._sim_pause_button)
        self._sim_commit_button = QtWidgets.QToolButton(self._simulate_page)
        self._sim_commit_button.setObjectName("_sim_commit_button")
        self.horizontalLayout.addWidget(self._sim_commit_button)
        self._sim_discard_button = QtWidgets.QToolButton(self._simulate_page)
        self._sim_discard_button.setObjectName("_sim_discard_button")
        self.horizontalLayout.addWidget(self._sim_discard_button)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self._sim_min_button = QtWidgets.QPushButton(self._simulate_page)
        self._sim_min_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self._sim_min_button.setObjectName("_sim_min_button")
        self.horizontalLayout_7.addWidget(self._sim_min_button)
        self._sim_equil_button = QtWidgets.QPushButton(self._simulate_page)
        self._sim_equil_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self._sim_equil_button.setObjectName("_sim_equil_button")
        self.horizontalLayout_7.addWidget(self._sim_equil_button)
        self._sim_hide_surroundings_toggle = QtWidgets.QCheckBox(self._simulate_page)
        self._sim_hide_surroundings_toggle.setChecked(True)
        self._sim_hide_surroundings_toggle.setObjectName("_sim_hide_surroundings_toggle")
        self.horizontalLayout_7.addWidget(self._sim_hide_surroundings_toggle)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self._sim_temp_label = QtWidgets.QLabel(self._simulate_page)
        self._sim_temp_label.setObjectName("_sim_temp_label")
        self.horizontalLayout_7.addWidget(self._sim_temp_label)
        self._sim_temp_spin_box = QtWidgets.QDoubleSpinBox(self._simulate_page)
        self._sim_temp_spin_box.setDecimals(1)
        self._sim_temp_spin_box.setMaximum(500.0)
        self._sim_temp_spin_box.setSingleStep(10.0)
        self._sim_temp_spin_box.setProperty("value", 100.0)
        self._sim_temp_spin_box.setObjectName("_sim_temp_spin_box")
        self.horizontalLayout_7.addWidget(self._sim_temp_spin_box)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.toolBox.addItem(self._simulate_page, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self._undo_redo_frame = QtWidgets.QFrame(isolde_widget)
        self._undo_redo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._undo_redo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._undo_redo_frame.setObjectName("_undo_redo_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._undo_redo_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._undo_button = QtWidgets.QPushButton(self._undo_redo_frame)
        self._undo_button.setObjectName("_undo_button")
        self.horizontalLayout_2.addWidget(self._undo_button)
        self._redo_button = QtWidgets.QPushButton(self._undo_redo_frame)
        self._redo_button.setObjectName("_redo_button")
        self.horizontalLayout_2.addWidget(self._redo_button)
        self.verticalLayout_3.addWidget(self._undo_redo_frame)
        self._experience_level_frame = QtWidgets.QFrame(isolde_widget)
        self._experience_level_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._experience_level_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._experience_level_frame.setObjectName("_experience_level_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self._experience_level_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self._experience_level_label = QtWidgets.QLabel(self._experience_level_frame)
        self._experience_level_label.setObjectName("_experience_level_label")
        self.horizontalLayout_3.addWidget(self._experience_level_label)
        self._experience_level_combo_box = QtWidgets.QComboBox(self._experience_level_frame)
        self._experience_level_combo_box.setObjectName("_experience_level_combo_box")
        self._experience_level_combo_box.addItem("")
        self._experience_level_combo_box.addItem("")
        self._experience_level_combo_box.addItem("")
        self.horizontalLayout_3.addWidget(self._experience_level_combo_box)
        self.verticalLayout_3.addWidget(self._experience_level_frame)

        self.retranslateUi(isolde_widget)
        self.toolBox.setCurrentIndex(1)
        self._build_tab_widget.setCurrentIndex(1)
        self._sim_tab_widget.setCurrentIndex(2)
        self._restraints_pep_on_off_combo_box.setCurrentIndex(1)
        self._restraints_pep_all_sel_combo_box.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(isolde_widget)

    def retranslateUi(self, isolde_widget):
        _translate = QtCore.QCoreApplication.translate
        isolde_widget.setWindowTitle(_translate("isolde_widget", "Frame"))
        self.label_32.setText(_translate("isolde_widget", "Working on: "))
        self._build_tab_widget.setTabText(self._build_tab_widget.indexOf(self.tab), _translate("isolde_widget", "Tab 1"))
        self._build_tab_widget.setTabText(self._build_tab_widget.indexOf(self.tab_2), _translate("isolde_widget", "Tab 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self._build_page), _translate("isolde_widget", "Build"))
        self._sim_basic_selection_mode_group_box.setTitle(_translate("isolde_widget", "Simulation selection mode"))
        self._sim_basic_by_selected_atoms_button.setText(_translate("isolde_widget", "By selected atom(s)"))
        self._sim_basic_by_chain_button.setText(_translate("isolde_widget", "By chain(s)"))
        self._sim_basic_whole_structure_button.setText(_translate("isolde_widget", "Entire structure"))
        self._sim_basic_custom_selection_button.setText(_translate("isolde_widget", "Custom selection"))
        self.label_2.setText(_translate("isolde_widget", "Mobilise selected residue(s) "))
        self.label_3.setText(_translate("isolde_widget", "plus"))
        self.label_4.setText(_translate("isolde_widget", "residues before and after"))
        self.label_5.setText(_translate("isolde_widget", "plus residues coming within"))
        self.label_6.setText(_translate("isolde_widget", "Angstroms"))
        self._sim_basic_mobile_sel_backbone_checkbox.setText(_translate("isolde_widget", "Include backbone atoms of surrounding residues"))
        self.label_8.setText(_translate("isolde_widget", "Chains: "))
        self._sim_basic_mobile_chains_surrounds_label1.setText(_translate("isolde_widget", "Plus residues coming within"))
        self.label_9.setText(_translate("isolde_widget", "Angstroms"))
        self.label_11.setText(_translate("isolde_widget", "Include backbone atoms of surrounding residues"))
        self.label_7.setText(_translate("isolde_widget", "Mobile selection:"))
        self._sim_basic_mode_combo_box.setItemText(0, _translate("isolde_widget", "Crystallography mode"))
        self._sim_basic_mode_combo_box.setItemText(1, _translate("isolde_widget", "EM mode"))
        self._sim_basic_mode_combo_box.setItemText(2, _translate("isolde_widget", "Free mode (no maps)"))
        self._sim_basic_xtal_init_open_button.setText(_translate("isolde_widget", "Initialise model/MTZ combo"))
        self.label_10.setText(_translate("isolde_widget", "Atomic model"))
        self._sim_basic_xtal_init_reflections_file_button.setText(_translate("isolde_widget", "Map MTZ:"))
        self._sim_basic_xtal_init_reflections_file_name.setText(_translate("isolde_widget", "None"))
        self._sim_basic_xtal_init_go_button.setText(_translate("isolde_widget", "Initialise"))
        self._sim_basic_xtal_init_done_button.setText(_translate("isolde_widget", "Done"))
        self.label_12.setText(_translate("isolde_widget", "Name: "))
        self.label_13.setText(_translate("isolde_widget", "Model: "))
        self.label_14.setText(_translate("isolde_widget", "Cutoff (Å): "))
        self.label_15.setText(_translate("isolde_widget", "Coupling constant: "))
        self.label_16.setText(_translate("isolde_widget", "Style:"))
        self.label_17.setText(_translate("isolde_widget", "Colour:"))
        self._em_map_masked_checkbox.setText(_translate("isolde_widget", "Mask to selection"))
        self.label_18.setText(_translate("isolde_widget", "Contour:"))
        self._em_map_set_button.setText(_translate("isolde_widget", "Set"))
        self._em_map_remove_button.setText(_translate("isolde_widget", "Remove"))
        self._em_map_done_button.setText(_translate("isolde_widget", "Done"))
        self._sim_basic_em_map_button.setText(_translate("isolde_widget", "Choose map(s)"))
        self._sim_force_field_selection_label.setText(_translate("isolde_widget", "MD Forcefield:"))
        self._sim_water_model_selection_label.setText(_translate("isolde_widget", "Water model"))
        self.label.setText(_translate("isolde_widget", "Computational Platform:"))
        self._sim_tab_widget.setTabText(self._sim_tab_widget.indexOf(self._sim_basic_tab), _translate("isolde_widget", "Sim settings"))
        self._restraints_pep_on_off_combo_box.setItemText(0, _translate("isolde_widget", "Disable"))
        self._restraints_pep_on_off_combo_box.setItemText(1, _translate("isolde_widget", "Enable"))
        self.label_19.setText(_translate("isolde_widget", "peptide bond restraints for"))
        self._restraints_pep_all_sel_combo_box.setItemText(0, _translate("isolde_widget", "all"))
        self._restraints_pep_all_sel_combo_box.setItemText(1, _translate("isolde_widget", "selected"))
        self.label_20.setText(_translate("isolde_widget", "residues"))
        self._restraints_pep_go_button.setText(_translate("isolde_widget", "Make it so"))
        self.pushButton.setText(_translate("isolde_widget", "PushButton"))
        self._sim_tab_widget.setTabText(self._sim_tab_widget.indexOf(self._sim_restrain_tab), _translate("isolde_widget", "Custom restraints"))
        self.label_28.setText(_translate("isolde_widget", "Set rotamer:"))
        self._rebuild_sel_res_pep_info.setText(_translate("isolde_widget", "Placeholder"))
        self._rebuild_sel_res_rot_discard_button.setText(_translate("isolde_widget", "Clear"))
        self._rebuild_sel_res_rot_target_button.setText(_translate("isolde_widget", "Set target"))
        self.label_25.setText(_translate("isolde_widget", "Current peptide conformation:"))
        self._rebuild_sel_res_rot_info.setText(_translate("isolde_widget", "Placeholder"))
        self._rebuild_sel_res_rot_commit_button.setText(_translate("isolde_widget", "Commit"))
        self.label_24.setText(_translate("isolde_widget", "Selected residue:"))
        self._rebuild_sel_res_pep_flip_button.setText(_translate("isolde_widget", "Flip"))
        self._rebuild_sel_residue_info.setText(_translate("isolde_widget", "Placeholder"))
        self._sim_tab_widget.setTabText(self._sim_tab_widget.indexOf(self._sim_remodel_tab), _translate("isolde_widget", "Rebuild"))
        self.label_22.setText(_translate("isolde_widget", "Ramachandran Plot"))
        self._validate_rama_show_button.setText(_translate("isolde_widget", "Show"))
        self.label_21.setText(_translate("isolde_widget", "Ramachandran Plot"))
        self._validate_rama_case_combo_box.setItemText(0, _translate("isolde_widget", "General"))
        self._validate_rama_case_combo_box.setItemText(1, _translate("isolde_widget", "Glycine"))
        self._validate_rama_case_combo_box.setItemText(2, _translate("isolde_widget", "Isoleucine/Valine"))
        self._validate_rama_case_combo_box.setItemText(3, _translate("isolde_widget", "Preceding Proline"))
        self._validate_rama_case_combo_box.setItemText(4, _translate("isolde_widget", "Trans Proline"))
        self._validate_rama_case_combo_box.setItemText(5, _translate("isolde_widget", "Cis Proline"))
        self._validate_rama_hide_button.setText(_translate("isolde_widget", "Hide"))
        self._validate_rama_sel_combo_box.setItemText(0, _translate("isolde_widget", "Selected only"))
        self._validate_rama_sel_combo_box.setItemText(1, _translate("isolde_widget", "All"))
        self._validate_rama_go_button.setText(_translate("isolde_widget", "Make it so"))
        self.label_26.setText(_translate("isolde_widget", "Peptide bond geometry"))
        self._validate_pep_show_button.setText(_translate("isolde_widget", "Show"))
        self.label_27.setText(_translate("isolde_widget", "Peptide biond geometry"))
        self._validate_pep_hide_button.setText(_translate("isolde_widget", "Hide"))
        self.label_29.setText(_translate("isolde_widget", "Cis"))
        self.label_30.setText(_translate("isolde_widget", "Twisted"))
        self._validate_pep_update_button.setText(_translate("isolde_widget", "Update list"))
        self._sim_tab_widget.setTabText(self._sim_tab_widget.indexOf(self._sim_validate_tab), _translate("isolde_widget", "Validate"))
        self._sim_go_button.setText(_translate("isolde_widget", "Go"))
        self._sim_pause_button.setText(_translate("isolde_widget", "Pause"))
        self._sim_commit_button.setText(_translate("isolde_widget", "Save changes"))
        self._sim_discard_button.setText(_translate("isolde_widget", "Discard changes"))
        self._sim_min_button.setText(_translate("isolde_widget", "Min"))
        self._sim_equil_button.setText(_translate("isolde_widget", "Equil"))
        self._sim_hide_surroundings_toggle.setText(_translate("isolde_widget", "Hide surroundings"))
        self._sim_temp_label.setText(_translate("isolde_widget", "Temperature (K)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self._simulate_page), _translate("isolde_widget", "Simulate"))
        self._undo_button.setText(_translate("isolde_widget", "Undo"))
        self._redo_button.setText(_translate("isolde_widget", "Redo"))
        self._experience_level_label.setText(_translate("isolde_widget", "Experience level"))
        self._experience_level_combo_box.setItemText(0, _translate("isolde_widget", "Beginner"))
        self._experience_level_combo_box.setItemText(1, _translate("isolde_widget", "Intermediate"))
        self._experience_level_combo_box.setItemText(2, _translate("isolde_widget", "Developer"))

from . import resources_rc
