filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Tic20, Welcome to Coot version 0.8.6")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon tic20. Welcome to Coot 0.8.6")
set_display_lists_for_maps (0)
use_graphics_interface_state ()
