(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Tic20, Welcome to Coot version 0.8.6")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon tic20. Welcome to Coot 0.8.6")
(set-display-lists-for-maps 0)
(use-graphics-interface-state)
