(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Tic20, Welcome to Coot version 0.8.6")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning tic20. Welcome to Coot 0.8.6")
(set-display-lists-for-maps 0)
(use-graphics-interface-state)
(get-eds-pdb-and-mtz "4qiw")
(info-dialog "This map (4qiw) is marked by the EDS as "not a reliable map"")
(handle-read-draw-molecule-with-recentre "coot-download/pdb4qiw.ent" 1)
(make-and-draw-map "coot-download/4qiw_sigmaa.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "coot-download/4qiw_sigmaa.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-clipping-front  0.26)
(set-clipping-back  0.52)
(set-clipping-front  1.92)
(set-clipping-back  3.58)
(set-clipping-front  3.46)
(set-clipping-back  5.00)
(set-clipping-front  5.40)
(set-clipping-back  7.34)
(set-clipping-front  7.10)
(set-clipping-back  8.80)
(set-clipping-front  7.76)
(set-clipping-back  8.42)
(set-clipping-front  7.60)
(set-clipping-back  7.44)
(set-clipping-front  6.26)
(set-clipping-back  4.92)
(set-clipping-front  2.26)
(set-clipping-back -1.74)
(set-clipping-front -1.30)
(set-clipping-back -4.86)
(set-clipping-front -4.18)
(set-clipping-back -7.06)
(set-clipping-front -5.00)
(set-clipping-back -5.82)
(close-molecule 0)
(close-molecule 1)
(close-molecule 2)
(get-eds-pdb-and-mtz "1y1v")
(handle-read-draw-molecule-with-recentre "coot-download/pdb1y1v.ent" 1)
(make-and-draw-map "coot-download/1y1v_sigmaa.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "coot-download/1y1v_sigmaa.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
