filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Tic20, Welcome to Coot version 0.8.6")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning tic20. Welcome to Coot 0.8.6")
set_display_lists_for_maps (0)
use_graphics_interface_state ()
;; # DIRECT SCHEME ((get-eds-pdb-and-mtz "4qiw"))
info_dialog ("This map (4qiw) is marked by the EDS as "not a reliable map"")
handle_read_draw_molecule_with_recentre ("coot-download/pdb4qiw.ent", 1)
make_and_draw_map ("coot-download/4qiw_sigmaa.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("coot-download/4qiw_sigmaa.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_clipping_front ( 0.26)
set_clipping_back ( 0.52)
set_clipping_front ( 1.92)
set_clipping_back ( 3.58)
set_clipping_front ( 3.46)
set_clipping_back ( 5.00)
set_clipping_front ( 5.40)
set_clipping_back ( 7.34)
set_clipping_front ( 7.10)
set_clipping_back ( 8.80)
set_clipping_front ( 7.76)
set_clipping_back ( 8.42)
set_clipping_front ( 7.60)
set_clipping_back ( 7.44)
set_clipping_front ( 6.26)
set_clipping_back ( 4.92)
set_clipping_front ( 2.26)
set_clipping_back (-1.74)
set_clipping_front (-1.30)
set_clipping_back (-4.86)
set_clipping_front (-4.18)
set_clipping_back (-7.06)
set_clipping_front (-5.00)
set_clipping_back (-5.82)
close_molecule (0)
close_molecule (1)
close_molecule (2)
;; # DIRECT SCHEME ((get-eds-pdb-and-mtz "1y1v"))
handle_read_draw_molecule_with_recentre ("coot-download/pdb1y1v.ent", 1)
make_and_draw_map ("coot-download/1y1v_sigmaa.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("coot-download/1y1v_sigmaa.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
